services:
  - type: web
    name: joyeria-nfc-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py ensure_admin
      python manage.py import_verses --path verses.csv --assign-general
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: SERVE_MEDIA
        value: "True"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
