# Generated by Django 6.0.1 on 2026-02-02 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('nfc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_editable', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.versecategory')),
                ('nfc_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfc.nfcdevice')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.bibleversion')),
            ],
        ),
        migrations.CreateModel(
            name='StudyVerseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nfc_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfc.nfcdevice')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.verse')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.bibleversion')),
            ],
        ),
    ]
