# Generated by Django 5.1.1 on 2026-02-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyverseassignment',
            name='nfc_device',
        ),
        migrations.RemoveField(
            model_name='studyverseassignment',
            name='version',
        ),
        migrations.AddField(
            model_name='experienceconfig',
            name='static_verse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.verse'),
        ),
        migrations.AddField(
            model_name='studyverseassignment',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_verses', to='experiences.experienceconfig'),
        ),
    ]
