# Generated by Django 6.0.1 on 2026-02-02 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFCDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uid', models.CharField(max_length=100, unique=True)),
                ('experience_type', models.CharField(choices=[('DAILY', 'Versículo diario'), ('CATEGORY', 'Por categoría'), ('STATIC', 'Versículo estático'), ('STUDY', 'Estudio editable')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NFCScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('nfc_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfc.nfcdevice')),
            ],
        ),
    ]
