# Generated by Django 5.1.1 on 2026-02-10 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcdevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nfcdevice',
            name='experience_type',
            field=models.CharField(choices=[('DAILY', 'VersÃ\xadculo diario'), ('CATEGORY', 'Por categorÃ\xada'), ('STATIC', 'VersÃ\xadculo estÃ¡tico'), ('STUDY', 'Estudio editable')], max_length=20),
        ),
    ]
